steps:
# 1. Build the Docker image for the website
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}',
    '.'
  ]

# 2. Push the Docker image to Google Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}'
  ]

# 3. Deploy the backend Cloud Function
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions', 'deploy', '${_FUNCTION_NAME}',
    '--source=./functions',
    '--runtime=nodejs20',
    '--trigger-http',
    '--allow-unauthenticated',
    '--region=${_REGION}'
  ]
  id: 'Deploy Cloud Function'

# 4. Deploy the website container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'deploy', '${_SERVICE_NAME}',
    '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}',
    '--region=${_REGION}',
    '--allow-unauthenticated'
  ]
  id: 'Deploy to Cloud Run'

# This section lists the container image we built so Cloud Build can clean it up later.
images:
- '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}'
