steps:
  # Step 1: Install dependencies for the Next.js frontend
  - name: 'node:20'
    entrypoint: npm
    args: ['install']
    dir: '.'

  # Step 2: Build the Next.js application
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
    dir: '.'
    env:
      - 'NEXT_PUBLIC_ORDER_FUNCTION_URL=${_ORDER_FUNCTION_URL}'

  # Step 3: Deploy the Next.js app to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'battery-upgrade-website'
      - '--source=.'
      - '--platform=managed'
      - '--region=${_REGION}'
      - '--allow-unauthenticated'
      - '--port=3000'

  # Step 4: Deploy the Cloud Function
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'submitOrder'
      - '--runtime=nodejs20'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--region=${_REGION}'
      - '--source=./functions'
      - '--entry-point=submitOrder'
      - '--set-env-vars=GOOGLE_CLOUD_PROJECT=${PROJECT_ID}'

substitutions:
  _REGION: 'us-central1'
  _ORDER_FUNCTION_URL: 'https://${_REGION}-${PROJECT_ID}.cloudfunctions.net/submitOrder'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1800s'
