#!/bin/bash

# Deployment script for Battery Upgrade Website
# This script deploys both the Cloud Function and the Next.js frontend

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Check if gcloud is installed
if ! command -v gcloud &> /dev/null; then
    print_error "gcloud CLI is not installed. Please install it first."
    echo "Visit: https://cloud.google.com/sdk/docs/install"
    exit 1
fi

# Get project ID
PROJECT_ID=$(gcloud config get-value project 2>/dev/null)

if [ -z "$PROJECT_ID" ]; then
    print_error "No GCP project is set. Please set your project:"
    echo "  gcloud config set project YOUR_PROJECT_ID"
    exit 1
fi

print_info "Using GCP Project: $PROJECT_ID"

# Set default region
REGION=${REGION:-us-central1}
print_info "Using region: $REGION"

# Ask for confirmation
echo ""
read -p "Do you want to deploy to project '$PROJECT_ID' in region '$REGION'? (y/n) " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    print_warning "Deployment cancelled"
    exit 0
fi

echo ""
print_info "Starting deployment..."
echo ""

# Step 1: Deploy Cloud Function
print_info "Step 1/3: Deploying Cloud Function..."
cd functions

if [ ! -d "node_modules" ]; then
    print_info "Installing Cloud Function dependencies..."
    npm install
fi

gcloud functions deploy submitOrder \
    --runtime nodejs20 \
    --trigger-http \
    --allow-unauthenticated \
    --region $REGION \
    --entry-point submitOrder \
    --set-env-vars GOOGLE_CLOUD_PROJECT=$PROJECT_ID

FUNCTION_URL="https://$REGION-$PROJECT_ID.cloudfunctions.net/submitOrder"
print_success "Cloud Function deployed successfully!"
print_info "Function URL: $FUNCTION_URL"

cd ..

# Step 2: Update environment variable
print_info "Step 2/3: Updating environment variables..."

cat > .env.local << EOF
# Auto-generated by deploy.sh
NEXT_PUBLIC_ORDER_FUNCTION_URL=$FUNCTION_URL
EOF

print_success "Environment variables updated"

# Step 3: Deploy to Cloud Run
print_info "Step 3/3: Deploying Next.js app to Cloud Run..."

gcloud run deploy battery-upgrade-website \
    --source . \
    --platform managed \
    --region $REGION \
    --allow-unauthenticated \
    --port 3000 \
    --set-env-vars NEXT_PUBLIC_ORDER_FUNCTION_URL=$FUNCTION_URL

# Get the Cloud Run URL
WEBSITE_URL=$(gcloud run services describe battery-upgrade-website \
    --region $REGION \
    --format 'value(status.url)')

echo ""
print_success "🎉 Deployment completed successfully!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
print_info "Your website is now live at:"
echo "  $WEBSITE_URL"
echo ""
print_info "Cloud Function URL:"
echo "  $FUNCTION_URL"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
print_info "Next steps:"
echo "  1. Test your website by visiting the URL above"
echo "  2. Submit a test order to verify the integration"
echo "  3. Check Firestore console for the order data"
echo "  4. Configure a custom domain (optional)"
echo ""
print_warning "Note: The first request may take a few seconds as Cloud Run starts up"
echo ""
